stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_NAME: my-app
  DOCKER_IMAGE_TAG: stable


default:
  image: 
    name: docker:23.0.5
    entrypoint: [""]
  services:
    - docker:23.0.5-dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"





build:
  stage: build
  script:
    - echo "♥♥♥♥♥♥ building docker images"
    - docker build -t $DOCKER_IMAGE_NAME-nginx:$DOCKER_IMAGE_TAG -f nginx/Dockerfile nginx
    - docker build -t $DOCKER_IMAGE_NAME-service1:$DOCKER_IMAGE_TAG -f service1/Dockerfile service1
    - docker build -t $DOCKER_IMAGE_NAME-service2:$DOCKER_IMAGE_TAG -f service2/Dockerfile service2
    - docker images


test:
  stage: test
  script:
    - echo "♥♥♥♥♥♥♥♥ running tests"
    - docker run --rm $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG python /app/tests/run_tests.py


deploy:
  stage: deploy
  services:
  script:
    - echo "♥♥♥♥♥ deploying the system"
    - docker-compose down || true
    - docker-compose up -d --build

  when: on_success





