stages:
  - build
  - test
  - deploy

services:
  - name: docker:20.10-dind
    alias: docker

variables:
  #DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  # Point Docker CLI to the DinD service
  DOCKER_HOST: "tcp://docker:2375"
  # Use overlay2 which is often recommended
  DOCKER_DRIVER: overlay2

default:
  image: docker:20.10

build:
  stage: build
  script:
    - echo "♥♥♥♥♥♥ building docker imgages"    
    - docker info
    - docker build -t devops-project .


test:
  stage: test
  script:
    - echo "♥♥♥♥♥♥♥♥ running tests"
    - docker run --rm devops-project python /app/tests/run_tests.py


deploy:
  stage: deploy
  services:
  script:
    - echo "♥♥♥♥♥ deploying the system"
    - docker-compose down || true
    - docker-compose up -d --build

  when: on_success


